M = {
 "M01 # anywhere is preprocessor": ('if ch == "#" and line_start:', 'if ch == "#":'),
 "M02 line_start never cleared": ('        line_start = False\n        if text.startswith("//", i) or', '        if text.startswith("//", i) or'),
 "M03 unterminated /* to EOF": ('            if close == -1:\n                eol = text.find("\\n", i)\n                i = n if eol == -1 else eol', '            if close == -1:\n                i = n'),
 "M04 block comment rows not counted": ('            row += text.count("\\n", i, end)\n', ''),
 "M05 literal rows not counted": ('            row += text.count("\\n", i, literal_end)\n', ''),
 "M06 literal emits no token": ("            tokens.append(_CSharpToken('\"', row))\n", ''),
 "M07 //// is doc": ('        return not text.startswith("////", i)', '        return True'),
 "M08 /*** is doc": ('text[i + 3:i + 4] not in ("*", "/")', 'text[i + 3:i + 4] != "/"'),
 "M09 /**/ is doc": ('text[i + 3:i + 4] not in ("*", "/")', 'text[i + 3:i + 4] != "*"'),
 "M10 every comment anchors": ('            if _csharp_is_doc_opener(text, i):\n', '            if True:\n'),
 "M11 boundary drop ]": ('_CSHARP_MEMBER_BOUNDARY = frozenset({";", "{", "}", "]"})', '_CSHARP_MEMBER_BOUNDARY = frozenset({";", "{", "}"})'),
 "M12 boundary drop ;": ('_CSHARP_MEMBER_BOUNDARY = frozenset({";", "{", "}", "]"})', '_CSHARP_MEMBER_BOUNDARY = frozenset({"{", "}", "]"})'),
 "M13 boundary drop {": ('_CSHARP_MEMBER_BOUNDARY = frozenset({";", "{", "}", "]"})', '_CSHARP_MEMBER_BOUNDARY = frozenset({";", "}", "]"})'),
 "M14 boundary drop }": ('_CSHARP_MEMBER_BOUNDARY = frozenset({";", "{", "}", "]"})', '_CSHARP_MEMBER_BOUNDARY = frozenset({";", "{", "]"})'),
 "M15 boundary add )": ('_CSHARP_MEMBER_BOUNDARY = frozenset({";", "{", "}", "]"})', '_CSHARP_MEMBER_BOUNDARY = frozenset({";", "{", "}", "]", ")"})'),
 "M16 any [ opens section": ('return tokens[k].text == "[" and (k == 0 or tokens[k - 1].text in _CSHARP_MEMBER_BOUNDARY)', 'return tokens[k].text == "["'),
 "M17 file start not a boundary": ('(k == 0 or tokens[k - 1].text in _CSHARP_MEMBER_BOUNDARY)', '(k > 0 and tokens[k - 1].text in _CSHARP_MEMBER_BOUNDARY)'),
 "M18 bracket no nesting": ('            depth -= 1\n            if depth == 0:\n                return k', '            return k'),
 "M19 names any depth": ('            if depth == 1 and tokens[k - 1]', '            if depth >= 1 and tokens[k - 1]'),
 "M20 parens not depth-tracked": ('depth += 1 if text in "([" else 0\n            depth -= 1 if text in ")]" else 0', 'depth += 1 if text == "[" else 0\n            depth -= 1 if text == "]" else 0'),
 "M21 no target prefix": ('tokens[k - 1].text in "[,:"', 'tokens[k - 1].text in "[,"'),
 "M22 first dotted part": ('                names.append(tokens[dotted].text)', '                names.append(tokens[k].text)'),
 "M23 stop drop =": ('_CSHARP_STOP_BEFORE_NAME = frozenset({";", "{", "}", "=", "=>"})', '_CSHARP_STOP_BEFORE_NAME = frozenset({";", "{", "}", "=>"})'),
 "M24 stop drop =>": ('_CSHARP_STOP_BEFORE_NAME = frozenset({";", "{", "}", "=", "=>"})', '_CSHARP_STOP_BEFORE_NAME = frozenset({";", "{", "}", "="})'),
 "M25 stop drop ;": ('_CSHARP_STOP_BEFORE_NAME = frozenset({";", "{", "}", "=", "=>"})', '_CSHARP_STOP_BEFORE_NAME = frozenset({"{", "}", "=", "=>"})'),
 "M26 stop drop {": ('_CSHARP_STOP_BEFORE_NAME = frozenset({";", "{", "}", "=", "=>"})', '_CSHARP_STOP_BEFORE_NAME = frozenset({";", "}", "=", "=>"})'),
 "M27 stop drop }": ('_CSHARP_STOP_BEFORE_NAME = frozenset({";", "{", "}", "=", "=>"})', '_CSHARP_STOP_BEFORE_NAME = frozenset({";", "{", "=", "=>"})'),
 "M28 no generic skip": ('            if tokens[name_k].text == ">":', '            if False:'),
 "M29 no dedup": ('        if name is None or name.row in seen_rows:', '        if name is None:'),
 "M30 row 0-based": ('        row = name.row + 1', '        row = name.row'),
 "M31 => width 1": ('width = 2 if text.startswith("=>", i) else 1', 'width = 1'),
 "M32 before: single section": ('        sections.append((open_k, k))\n        k = open_k', '        sections.append((open_k, k))\n        break'),
 "M33 after: single section": ('        sections.append((k, close_k + 1))\n        k = close_k + 1', '        sections.append((k, close_k + 1))\n        k = close_k + 1\n        break'),
 "M34 before not opener-checked": ('        if open_k is None or not _csharp_opens_attribute_section(tokens, open_k):', '        if open_k is None:'),
 "M35 ignore before sections": ('names = _csharp_attribute_names(tokens, before + after)', 'names = _csharp_attribute_names(tokens, after)'),
 "M36 ignore after sections": ('names = _csharp_attribute_names(tokens, before + after)', 'names = _csharp_attribute_names(tokens, before)'),
 "M37 \\r not whitespace": ('if ch in " \\t\\r\\f\\v":', 'if ch in " \\t\\f\\v":'),
 "M38 no literal skip": ('        literal_end = _csharp_try_skip_literal(text, i)\n        if literal_end is not None:\n            tokens.append', '        literal_end = None\n        if literal_end is not None:\n            tokens.append'),
 "M39 name any first char": ('tokens[name_k] if name_k >= 0 and tokens[name_k].text[0].isalpha() else None', 'tokens[name_k] if name_k >= 0 else None'),
 "M40 # skips only char": ('        if ch == "#" and line_start:\n            eol = text.find("\\n", i)\n            i = n if eol == -1 else eol', '        if ch == "#" and line_start:\n            i += 1'),
 "M41 @ not ident start": ('if ch.isalnum() or ch in "_@":', 'if ch.isalnum() or ch == "_":'),
 "M42 name excludes _": ('(text[0].isalpha() or text[0] == "_")', 'text[0].isalpha()'),
 "M43 line_start cleared before #": ('        if ch == "#" and line_start:', '        line_start = False\n        if ch == "#" and line_start:'),
 "M44 // is block": ('            if text[i + 1] == "/":', '            if False and text[i + 1] == "/":'),
 "M45 attribute suffix no strip": ('name.removesuffix("Attribute") in _CSHARP_TEST_ATTRIBUTE_NAMES', 'False'),
 "M46 generic skip one less": ('                name_k -= 1\n            return tokens[name_k]', '            return tokens[name_k]'),
}
